import { Country } from "../types/enums";
import type { Player } from "../types/player";
import type { Stats } from "../types/stats";
import type { Team } from "../types/team";
import type { Tournament } from "../types/tournament";
import type { Trophy } from "../types/trophy";

export const MOCK_STATS: Record<string, Stats> = {
  s1mple: {
    id: 1,
    adr: 84.5,
    kills: 14200,
    deaths: 10100,
    assists: 2300,
    fpr: 0.81,
    utilityDamage: 11.2,
    kr: 0.84,
    entrySuccess: 61.5,
    clutchSuccess: 68.2,
    headshot: 41.2,
    flashSuccess: 45.0,
  },
  b1t: {
    id: 2,
    adr: 75.8,
    kills: 9800,
    deaths: 8200,
    assists: 1900,
    fpr: 0.7,
    utilityDamage: 14.5,
    kr: 0.72,
    entrySuccess: 52.1,
    clutchSuccess: 54.3,
    headshot: 64.5,
    flashSuccess: 38.2,
  },
  jl: {
    id: 3,
    adr: 78.2,
    kills: 8900,
    deaths: 8100,
    assists: 2100,
    fpr: 0.72,
    utilityDamage: 18.1,
    kr: 0.73,
    entrySuccess: 55.4,
    clutchSuccess: 61.0,
    headshot: 51.8,
    flashSuccess: 42.1,
  },
  zywoo: {
    id: 4,
    adr: 82.1,
    kills: 12400,
    deaths: 9300,
    assists: 1800,
    fpr: 0.79,
    utilityDamage: 9.8,
    kr: 0.81,
    entrySuccess: 59.0,
    clutchSuccess: 65.4,
    headshot: 39.5,
    flashSuccess: 36.4,
  },
  ropz: {
    id: 5,
    adr: 79.4,
    kills: 11200,
    deaths: 8900,
    assists: 2050,
    fpr: 0.74,
    utilityDamage: 15.3,
    kr: 0.75,
    entrySuccess: 54.0,
    clutchSuccess: 63.8,
    headshot: 53.1,
    flashSuccess: 40.0,
  },
};

export const MOCK_PLAYERS: Player[] = [
  {
    id: 1,
    nick: "s1mple",
    firstname: "Oleksandr",
    surname: "Kostyliev",
    country: Country.Ukraine,
    dateOfBirth: "1997-10-02",
    teamId: 1,
    photo: "https://img-cdn.hltv.org/player-portrait/s1mple.png",
    trophyIds: [101, 102],
    stats: MOCK_STATS.s1mple,
  },
  {
    id: 2,
    nick: "b1t",
    firstname: "Valeriy",
    surname: "Vakhovskiy",
    country: Country.Ukraine,
    dateOfBirth: "2003-01-05",
    teamId: 1,
    photo: "https://img-cdn.hltv.org/player-portrait/b1t.png",
    trophyIds: [101, 102],
    stats: MOCK_STATS.b1t,
  },
  {
    id: 3,
    nick: "jL",
    firstname: "Justinas",
    surname: "Lekavicius",
    country: Country.Lithuania,
    dateOfBirth: "1999-09-29",
    teamId: 1,
    photo: "https://img-cdn.hltv.org/player-portrait/jl.png",
    trophyIds: [102],
    stats: MOCK_STATS.jl,
  },
  {
    id: 4,
    nick: "ZywOo",
    firstname: "Mathieu",
    surname: "Herbaut",
    country: Country.France,
    dateOfBirth: "2000-11-09",
    teamId: 2,
    photo: "https://img-cdn.hltv.org/player-portrait/zywoo.png",
    trophyIds: [103],
    stats: MOCK_STATS.zywoo,
  },
  {
    id: 5,
    nick: "ropz",
    firstname: "Robin",
    surname: "Kool",
    country: Country.Estonia,
    dateOfBirth: "1999-12-22",
    teamId: 3,
    photo: "https://img-cdn.hltv.org/player-portrait/ropz.png",
    trophyIds: [],
    stats: MOCK_STATS.ropz,
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 1,
    name: "Natus Vincere",
    logo: "https://img-cdn.hltv.org/teamlogo/navi.svg",
    players: MOCK_PLAYERS.filter((p) => p.teamId === 1),
    trophies: [101, 102],
    country: Country.Ukraine,
  },
  {
    id: 2,
    name: "Team Vitality",
    logo: "https://img-cdn.hltv.org/teamlogo/vitality.svg",
    players: MOCK_PLAYERS.filter((p) => p.teamId === 2),
    trophies: [103],
    country: Country.France,
  },
  {
    id: 3,
    name: "FaZe Clan",
    logo: "https://img-cdn.hltv.org/teamlogo/faze.svg",
    players: MOCK_PLAYERS.filter((p) => p.teamId === 3),
    trophies: [],
    country: Country.UnitedStates,
  },
];

export const MOCK_TROPHIES: Trophy[] = [
  {
    id: 101,
    name: "PGL Major Stockholm 2021",
    image: "https://img-cdn.hltv.org/trophy/stockholm2021.png",
    team: MOCK_TEAMS[0], // NAVI
    tournamentId: 501,
    teamId: 1,
    winnerIds: [1, 2],
  },
  {
    id: 102,
    name: "PGL Major Copenhagen 2024",
    image: "https://img-cdn.hltv.org/trophy/copenhagen2024.png",
    team: MOCK_TEAMS[0],
    tournamentId: 502,
    teamId: 1,
    winnerIds: [2, 3],
  },
  {
    id: 103,
    name: "BLAST.tv Paris Major 2023",
    image: "https://img-cdn.hltv.org/trophy/paris2023.png",
    team: MOCK_TEAMS[1], 
    tournamentId: 503,
    teamId: 2,
    winnerIds: [4],
  },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 501,
    title: "PGL Major Stockholm 2021",
    prizepool: 2000000,
    mvp: MOCK_PLAYERS.find((p) => p.nick === "s1mple"),
    winner: MOCK_TEAMS.find((t) => t.id === 1),
    teams: MOCK_TEAMS,
    trophy: MOCK_TROPHIES[0],
  },
  {
    id: 502,
    title: "PGL Major Copenhagen 2024",
    prizepool: 1250000,
    mvp: MOCK_PLAYERS.find((p) => p.nick === "jL"),
    winner: MOCK_TEAMS.find((t) => t.id === 1),
    teams: MOCK_TEAMS,
    trophy: MOCK_TROPHIES[1],
  },
  {
    id: 503,
    title: "BLAST.tv Paris Major 2023",
    prizepool: 1250000,
    mvp: MOCK_PLAYERS.find((p) => p.nick === "ZywOo"),
    winner: MOCK_TEAMS.find((t) => t.id === 2),
    teams: [MOCK_TEAMS[1], MOCK_TEAMS[2]],
    trophy: MOCK_TROPHIES[2],
  },
];